# Conda environment specification
# To import/create a copy of the environment:
#    conda env create -f .environment.yml
name: east-africa-transport
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cartopy
  - fiona
  - geopandas
  - notebook
  - rasterio
  - rioxarray
  - shapely
  - tqdm
  - pip:
    - snkit
