# Read The Docs config
# - http://docs.readthedocs.io/en/latest/yaml-config.html

# python version
python:
  version: 3.9
  setup_py_install: true
  use_system_site_packages: true

requirements_file: requirements-docs.txt

# build html and pdf
formats:
  - pdf

build:
  image: testing
